name: Deploy VuePress site to GitHub Pages

on:
  push:
    branches:
      - master   # 当推送到 master 分支时触发部署

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build VuePress
        run: npm run build

      # 保证 dist 存在，然后加上 .nojekyll
      - name: Add .nojekyll
        run: |
          mkdir -p docs/.vuepress/dist
          touch docs/.vuepress/dist/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/.vuepress/dist
          enable_jekyll: false
